apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: onos
  name: onos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onos
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: onos
    spec:
      containers:
      - image: seclabdockerhub/sdnlabdockerhub:onos1.0
        name: onos
        resources: {}
status: {}
