apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ubuntu
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubuntu
    spec:
      containers:
      - image: seclabdockerhub/sdnlabdockerhub:ubuntu1.0
        name: ubuntu
        resources: {}
        command: ["/bin/bash","-c","--"]
        args: ["while true; do sleep 30; done;"]
        securityContext:
          privileged: true
status: {}
